version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: admin123 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: businesslink-db # The PostgreSQL default database (automatically created at first launch)
    volumes:
      # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
      # You don't need to create the `db-data` folder. Docker Compose will do it for you.
      - ./db-data/:/var/lib/postgresql/data/