version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
hooks:
  BeforeInstall:
    - location: scripts/setup.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
