---
apiVersion: v1
kind: Service
metadata:
  name: businesslinkcore
  labels:
    app: businesslinkcore
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  businesslinkcore-mapping
      prefix: /backend/businesslinkcore
      service: businesslinkcore:8020
      ---
      apiVersion: v1
      kind: Route
      metadata:
        name: businesslinkcore
      spec:
        port:
          targetPort: 8020
        to:
          kind: Service
          name: businesslinkcore

spec:
  type: NodePort
  selector:
    app: businesslinkcore
  ports:
    - protocol: TCP
      port: 8020
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: businesslinkcore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: businesslinkcore
    spec:
      containers:
        - name: businesslinkcore
          image: rchiarinelli/businesslink-core:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8020

