version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: admin123 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: businesslink-db # The PostgreSQL default database (automatically created at first launch)
    restart: unless-stopped

volumes:
  postgres-data:
