version: '3'
services:
  businesslinkcore:
    image: 'rchiarinelli/businesslink-core:latest'
    ports:
      - 80:8020
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: BUSINESS_LINK_DB
      SPRING_DATASOURCE_USER_NAME: BUSINESS_LINK_USERNAME
      SPRING_DATASOURCE_PASSWORD: BUSINESS_LINK_PASSWORD
