version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: admin123 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: businesslink-db # The PostgreSQL default database (automatically created at first launch)
    restart: unless-stopped

  businesslinkcore:
    image: 'rchiarinelli/businesslink-core:latest'
    ports:
      - 80:8020
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/businesslink-db

volumes:
  postgres-data:
